#!/bin/bash

# Source function library.
. /etc/init.d/functions

#exec="/opt/configtool/run.sh"
exec="gunicorn -c /opt/configtool/gunicorn.ini configtool:app --chdir /opt/configtool"
prog="configtool"

lockfile=/var/lock/subsys/$prog.pid

do_start() {
    echo -n $"Starting $prog ... "
    action `$exec`
    
}

do_stop() {
    echo "stopping $prog ... `killproc -p $lockfile`"
}

get_status() {
    echo "$prog `status -p $lockfile`"
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    status)
        get_status
        
        ;;
    restart)
        do_stop
        do_start
        ;;
        
    *)
        echo "Usage: <servicename> {start|stop|status|restart"
        exit 1
        ;;
esac
exit $?